routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\UsersController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Pages
Route::get('/blogs', [PagesController::class, 'blogs'])->name('page.blog');
Route::get('/media', [PagesController::class, 'media'])->name('page.media');
Route::get('/projecten', [PagesController::class, 'projects'])->name('page.project');
Route::get('/findpage/{id}', [PagesController::class, 'findpage'])->name('page.find');
Route::get('/', [PagesController::class, 'homepage'])->name('page.home');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::middleware(['auth', 'admin'])->group(function () {
    //adminpage
    Route::get('/media/{id}', [PagesController::class, 'show'])->name('media.show');
    Route::get('/create', [PagesController::class, 'create'])->name('page.create');
    Route::get('/remove', [PagesController::class, 'destroy'])->name('page.destroy');
    Route::get('/users', [PagesController::class, 'users'])->name('page.users');
    //Edit forms
    Route::get('/blog/edit/{id}', [BlogController::class, 'edit'])->name('blog.edit');
    Route::post('/blog/update/{id}', [BlogController::class, 'update'])->name('blog.update');
    Route::get('/project/edit/{id}', [ProjectController::class, 'edit'])->name('project.edit');
    Route::post('/project/update/{id}', [ProjectController::class, 'update'])->name('project.update');
    //Create forms
    Route::post('/blog/store', [BlogController::class, 'store'])->name('blog.store');
    Route::post('/media/store', [MediaController::class, 'store'])->name('media.store');
    Route::post('/project/store', [ProjectController::class, 'store'])->name('project.store');
    //Destroy forms
    Route::get('/blog/destroy/{id}', [BlogController::class, 'destroy'])->name('blog.destroy');
    Route::get('/project/destroy/{id}', [ProjectController::class, 'destroy'])->name('project.destroy');
    Route::get('/media/destroy/{id}', [MediaController::class, 'destroy'])->name('media.destroy');
    Route::get('/users/destroy/{id}', [UsersController::class, 'destroy'])->name('user.destroy');
    //admin settings
    Route::get('/admin/add/{id}', [UsersController::class, 'adminmaker'])->name('admin.add');
    Route::get('/admin/remove/{id}', [UsersController::class, 'adminremover'])->name('admin.remove');
});

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/admin/blogedit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="pt-12 pb-6">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <form action="{{ route('blog.update', $blog->id) }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="w-full">
                            <p>Titel</p>
                            <input value="{{ $blog->title }}" class="w-full h-12 p-5 mb-4 rounded border-2 border-slate-200 hover:bg-slate-100" type="text" type="text" name="title" id="title" required>
                        </div>

                        <div class="w-full">
                            <p>Korte Beschrijving</p>
                            <input value="{{ $blog->description }}" class="w-full h-12 p-5 mb-4 rounded border-2 border-slate-200 hover:bg-slate-100" type="text" type="text" name="description" id="description" required>
                        </div>

                        <div class="w-full">
                            <p>Content</p>
                            <textarea name="content" id="content" rows="20" class="w-full mb-4 p-5 rounded border-2 border-slate-200 hover:bg-slate-100" required>{{ $blog->content }}</textarea>
                        </div>

                        <div class="w-full">
                            <p>Datum</p>
                            <input type="date" name="date" id="date" class="w-full p-5 mb-4 rounded border-2 border-slate-200 hover:bg-slate-100" value="{{ $blog->date }}" required>
                        </div>

                        <div class="w-full">
                            <p>Foto's / Thumbnail</p>
                            <input value="{{ $blog->imagepath }}" type="file" name="image" id="image" class="w-full p-5 mb-4 rounded border-2 border-slate-200 hover:bg-slate-100">
                        </div>

                        <div class="w-full">
                            <p>Aanmaken</p>
                            <input class="m-auto w-full text-center bg-white h-12 border-slate-200 border-2 hover:bg-slate-100" type="submit" type="submit" value="blog post aanmaken">
                        </div>
                    </form>
                </div>
            </div>
        </div>
</x-app-layout>

resources/views/admin/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="pt-12 pb-6">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <h1 class="mb-2 text-xl">Media Aanmaken</h1>
                    <form class="border-2 p-2 bg-slate-50 border-slate-100" action="{{ route('media.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="w-full">
                            <p>Foto's / Thumbnail</p>
                            <input type="file" multiple name="image" id="image" class="w-full p-5 mb-4 rounded border-2 border-slate-200 hover:bg-slate-100">
                        </div>

                        <div class="w-full">
                            <p>Aanmaken</p>
                            <input class="m-auto w-full text-center p-2 bg-white border-slate-200 border-2 hover:bg-slate-100" type="submit" type="submit" value="media post aanmaken">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="py-6">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <h1 class="mb-2 text-xl">Blog Post Aanmaken</h1>
                    <form class="border-2 p-2 bg-slate-50 border-slate-100" action="{{ route('blog.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="w-full">
                            <p>Titel</p>
                            <input class="w-full h-12 p-5 mb-4 rounded border-2 border-slate-200 hover:bg-slate-100" type="text" type="text" name="title" id="title" placeholder="ex: Learning Laravel, Dag: 1" required>
                        </div>

                        <div class="w-full">
                            <p>Korte Beschrijving</p>
                            <input class="w-full h-12 p-5 mb-4 rounded border-2 border-slate-200 hover:bg-slate-100" type="text" type="text" name="description" id="description" placeholder="ex: Op dag 1 heb ik software gedownload zoals.." required>
                        </div>

                        <div class="w-full">
                            <p>Content</p>
                            <textarea name="content" id="content" rows="20" class="w-full mb-4 p-5 rounded border-2 border-slate-200 hover:bg-slate-100" placeholder="ex: De start van mijn dag begon met een kopje thee waarna ik verder ging met mijn laravel blog website" required></textarea>
                        </div>

                        <div class="w-full">
                            <p>Datum</p>
                            <input type="date" name="date" id="date" class="w-full h-12 p-5 mb-4 rounded border-2 border-slate-200 hover:bg-slate-100" value="{{ date("Y-m-d") }}" required>
                        </div>

                        <div class="w-full">
                            <p>Foto's / Thumbnail</p>
                            <input type="file" name="image" id="image" class="w-full p-5 mb-4 rounded border-2 border-slate-200 hover:bg-slate-100">
                        </div>

                        <div class="w-full">
                            <p>Aanmaken</p>
                            <input class="m-auto w-full text-center bg-white h-12 border-slate-200 border-2 hover:bg-slate-100" type="submit" type="submit" value="blog post aanmaken">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="py-6">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <h1 class="mb-2 text-xl">Project Toevoegen</h1>
                    <form class="border-2 p-2 bg-slate-50 border-slate-100" action="{{ route('project.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="w-full">
                            <p>Titel</p>
                            <input class="w-full h-12 p-5 mb-4 rounded border-2 border-slate-200 hover:bg-slate-100" type="text" name="title" id="title" placeholder="ex: Learning Laravel, Dag: 1">
                        </div>

                        <div class="w-full">
                            <p>Link</p>
                            <input class="w-full h-12 p-5 mb-4 rounded border-2 border-slate-200 hover:bg-slate-100" type="text" name="link" id="link" placeholder="ex: Learning Laravel, Dag: 1">
                        </div>

                        <div class="w-full">
                            <p>Datum</p>
                            <input type="date" name="date" id="date" class="w-full p-5 mb-4 rounded border-2 border-slate-200 hover:bg-slate-100" value="{{ date("Y-m-d") }}">
                        </div>

                        <div class="w-full">
                            <p>Thumbnail</p>
                            <input type="file" name="image" id="image" class="w-full  p-5 mb-4 rounded border-2 border-slate-200 hover:bg-slate-100">
                        </div>

                        <div class="w-full">
                            <p>Aanmaken</p>
                            <input class="m-auto w-full text-center bg-white h-12 border-slate-200 border-2 hover:bg-slate-100" type="submit" value="project post aanmaken">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/destroy.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-6">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <p class="text-xl mb-1">Blogs</p> @if($blogs->isEmpty()) ( No Blogs Found ) @endif
                    <div class="border-slate-500/10 border-y-2 py-2">
                        @foreach($blogs as $blog)
                            <div class="flex align-middle">
                                <form method="GET" action="{{ route('blog.destroy', $blog->id) }}">
                                    @csrf
                                    <input name="_method" type="hidden" value="DELETE">
                                    <span class="flex">{{ $blog->title }} <p class="text-sm mr-1">( {{ substr($blog->description,0,25).'...' }} )</p><button type="submit" class="text-red-500 btn btn-xs btn-danger btn-flat show-alert-delete-box btn-sm" data-toggle="tooltip" title='delete'> Delete</button></span>
                                </form>
                                <p class="mx-1">or</p>
                                <form action="{{ route('blog.edit', $blog->id) }}" method="get">
                                    @csrf
                                    <button type="submit" class="text-blue-500 btn-flat btn-sm" data-toggle="tooltip" title='update'>Edit</button>
                                </form>
                            </div>
                        @endforeach
                    </div>
                    <br><br>
                    <p class="text-xl mb-1">Projects</p> @if($projects->isEmpty()) ( No Projects Found ) @endif
                    <div class="border-slate-500/10 border-y-2 py-2">
                        @foreach($projects as $project)
                            <div class="flex align-middle">
                                <form method="GET" action="{{ route('project.destroy', $project->id) }}">
                                    @csrf
                                    <input name="_method" type="hidden" value="DELETE">
                                    <span class="flex">{{ $project->title }} <p class="text-sm mr-1">( {{ $project->link }} )</p><button type="submit" class="text-red-500 btn btn-xs btn-danger btn-flat show-alert-delete-box btn-sm" data-toggle="tooltip" title='delete'> Delete</button></span>
                                </form>
                                <p class="mx-1">or</p>
                                <form action="{{ route('project.edit', $project->id) }}" method="get">
                                    @csrf
                                    <button type="submit" class="text-blue-500 btn-flat btn-sm" data-toggle="tooltip" title='update'>Edit</button>
                                </form>
                            </div>
                        @endforeach
                    </div>
                    <br><br>
                    <p class="text-xl mb-1">Media</p> @if($media->isEmpty()) ( No Media Found ) @endif
                    <div class="border-slate-500/10 border-y-2 py-2">
                        @foreach($media as $item)
                            <form method="GET" action="{{ route('media.destroy', $item->id) }}">
                                @csrf
                                <input name="_method" type="hidden" value="DELETE">
                                <a href="{{ route('media.show', $item->id) }}" target="_blank" class="image-link">{{ $item->imagepath }}</a>
                                <input type="submit" class="text-red-500 btn btn-xs btn-danger btn-flat show-alert-delete-box btn-sm" data-toggle="tooltip" title='delete' value="Delete">
                            </form>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script type="text/javascript">
        $('.show-alert-delete-box').click(function(event){
            const form =  $(this).closest("form");
            const name = $(this).data("name");
            event.preventDefault();
            swal({
                title: "Confirm Removal?",
                icon: "warning",
                type: "warning",
                buttons: ["Cancel","Ja!"],
                confirmButtonText: 'Ja, Delete!'
            }).then((willDelete) => {
                if (willDelete) {
                    form.submit();
                }
            });
        });
    </script>
</x-app-layout>

resources/views/admin/projectedit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="pt-12 pb-6">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <form action="{{ route('project.update', $project->id) }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="w-full">
                            <p>Titel</p>
                            <input value="{{ $project->title }}" class="w-full h-12 p-5 mb-4 rounded border-2 border-slate-200 hover:bg-slate-100" type="text" name="title" id="title" placeholder="ex: Learning Laravel, Dag: 1">
                        </div>

                        <div class="w-full">
                            <p>Link</p>
                            <input value="{{ $project->link }}" class="w-full h-12 p-5 mb-4 rounded border-2 border-slate-200 hover:bg-slate-100" type="text" name="link" id="link" placeholder="ex: Learning Laravel, Dag: 1">
                        </div>

                        <div class="w-full">
                            <p>Datum</p>
                            <input type="date" name="date" id="date" class="w-full h-12 p-5 mb-4 rounded border-2 border-slate-200 hover:bg-slate-100" value="{{ $project->date }}">
                        </div>

                        <div class="w-full">
                            <p>Thumbnail</p>
                            <input type="file" name="image" id="image" class="w-full p-5 mb-4 rounded border-2 border-slate-200 hover:bg-slate-100" value="{{ $project->imagepath }}">
                        </div>

                        <div class="w-full">
                            <p>Aanmaken</p>
                            <input class="m-auto w-full text-center bg-white h-12 border-slate-200 border-2 hover:bg-slate-100" type="submit" value="project post editen">
                        </div>
                    </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/users.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-6">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <p class="text-xl mb-1">Users</p> @if($users->isEmpty()) ( No Users Found ) @endif
                    <div class="border-slate-500/10 border-y-2 py-2">
                        @foreach($users as $user)
                            <div class="flex align-middle">
                                <form method="GET" action="{{ route('user.destroy', $user->id) }}">
                                    @csrf
                                    <input name="_method" type="hidden" value="DELETE">
                                    <span class="flex">{{ $user->name }} <p class="text-sm mr-1">( {{ substr($user->email,0,25).'...' }} )</p><button type="submit" class="text-red-500 btn btn-xs btn-danger btn-flat show-alert-delete-box btn-sm" data-toggle="tooltip" title='delete'> Delete</button></span>
                                </form>
                                @if($user->isAdmin === 1)
                                    <p class="mx-1">or</p>
                                    <form action="{{ route('admin.remove', $user->id) }}" method="get">
                                        @csrf
                                        <button type="submit" class="show-alert-remove-admin-box text-blue-500 btn-flat btn-sm" data-toggle="tooltip" title='update'>Remove Admin</button>
                                    </form>
                                @else
                                    <p class="mx-1">or</p>
                                    <form action="{{ route('admin.add', $user->id) }}" method="get">
                                        @csrf
                                        <button type="submit" class="show-alert-add-admin-box text-blue-500 btn-flat btn-sm" data-toggle="tooltip" title='update'>Make Admin</button>
                                    </form>
                                @endif

                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script type="text/javascript">
        $('.show-alert-delete-box').click(function(event){
            const form =  $(this).closest("form");
            const name = $(this).data("name");
            event.preventDefault();
            swal({
                title: "Confirm Removal?",
                icon: "warning",
                type: "warning",
                buttons: ["Cancel","Ja!"],
                confirmButtonText: 'Ja, Delete!'
            }).then((willDelete) => {
                if (willDelete) {
                    form.submit();
                }
            });
        });

        $('.show-alert-add-admin-box').click(function(event){
            const form =  $(this).closest("form");
            const name = $(this).data("name");
            event.preventDefault();
            swal({
                title: "Adding Admin?",
                icon: "warning",
                type: "warning",
                buttons: ["Cancel","Ja!"],
                confirmButtonText: 'Ja, Cancel!'
            }).then((willDelete) => {
                if (willDelete) {
                    form.submit();
                }
            });
        });

        $('.show-alert-remove-admin-box').click(function(event){
            const form =  $(this).closest("form");
            const name = $(this).data("name");
            event.preventDefault();
            swal({
                title: "Removing admin?",
                icon: "warning",
                type: "warning",
                buttons: ["Cancel","Ja!"],
                confirmButtonText: 'Ja, Cancel!'
            }).then((willDelete) => {
                if (willDelete) {
                    form.submit();
                }
            });
        });
    </script>
</x-app-layout>